# ~/.config/starship.toml

# Prompt format and alignment
format = """
$python\
$git_branch\
$git_status\
\n\
$directory\
$cmd_duration\
\n\
$character\
"""

# Working directory
[directory]
format = '[$path ](#85A0FF)'
truncation_length = 2
truncation_symbol = '/'

# Git
[git_branch]
format = '[git:\([$branch(:$remote_branch)](white)\) ](#FC97FF)'
[git_status]
format = '[$all_status$ahead_behind ]($style)'
modified = '[*](#f1502f)'
deleted = ''
untracked = ''
staged = ''
renamed = ''
diverged = ''
conflicted = ''
ahead = ''
behind = ''

# Langs
[python]
format = '[py:\([$virtualenv](white)\) ](#FFD343)'

# Command duration (only shows if command took longer than 2 seconds)
[cmd_duration]
format = '[$duration](white)'

# Prompt symbol
[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](red)'
